### ISSUE TITLE
Support Mac Address Pools in ovirt_permissions

### ISSUE THREAD

**Issue by dominikholler** [oVirt/ovirt-ansible-collection#128]
##### SUMMARY
[Bug 1863051 - [RFE] Allow management of permissions of MAC Address Pools via REST-API](https://bugzilla.redhat.com/show_bug.cgi?id=1863051) is adding permissions to MAC Address Pools.
This way, ovirt_permissions should allow the management of permissions of MAC Address Pools, too

##### COMPONENT NAME
ovirt_permissions

##### ADDITIONAL INFORMATION

```yaml
- ovirt_permissions:
    state: present
    user_name: user1
    authz_name: example.com-authz
    object_type: macpool
    object_name: pool1
    role: MacPoolUser
```
