### ISSUE TITLE
Ovirt_vms error when creating vm with pre-allocated disk from a pre-allocated disk template

### ISSUE THREAD

**Issue by github-lexaux** [oVirt/ovirt-ansible-collection#142]
##### SUMMARY
ansible 2.9.11
ovirt_engine-sdk4-4.4.4
ovirt_engine-4.3.10.4

Seems, the reported bug, wasn't resolved: https://github.com/ansible/ansible/issues/34154

We are getting the same error message reported in the bug

  "msg": "Fault reason is \"Operation Failed\". Fault detail is \"[Cannot add VM. Thin provisioned template disks can not be defined as Raw.]\". HTTP response code is 400."
}
The template has only one boot drive and this is the pre-allocated drive:  
template8_Disk1	Preallocated	VirtIO-SCSI	Image

##### COMPONENT NAME
ovirt_vm
##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by rbertol** [comment]
Hey Team,

@mnecas any update on this?

I have an environment where we are hitting the same issue.

**Comment by michalskrivanek** [comment]
use the clone=yes parameter to create a deep copy VM not linked to the parent template

**Comment by rbertol** [comment]
Hey @michalskrivanek,

Unfortunately, the clone option did not help to workaround the thin provisioning issue.

Following the snippet of the ovirt_vm task that we are running.

```
       - name: build vm
          ovirt_vm:
            auth:
              hostname: '{{ lookup("env","OVIRT_URL") }}'
              username: '{{ lookup("env","OVIRT_USERNAME") }}'
              password: '{{ lookup("env","OVIRT_PASSWORD") }}'
              kerberos: no
              insecure: yes
            state: running
            name: "{{ vm_name  }}"
            template: "{{ template_image }}"
            cluster: "{{ rhv_cluster }}"
            type: server
            clone: yes
            comment: "{{ cc_comment }}"
            cpu_cores: "{{ vm_cores }}"
            description: "{{ vm_description }}"
            high_availability: "{{ ha_choice }}"
            memory: "{{ vm_memory + 'GiB'}}"
            memory_guaranteed: "{{ vm_memory + 'GiB'}}"
            cloud_init_persist: true
            cloud_init:
              nic_boot_protocol: static
              nic_name: ens3
              nic_ip_address: "{{ ipaddr }}"
              nic_netmask: 255.255.255.0
              nic_gateway: "{{ gateway_setting }}"
              dns_servers: "{{ dns_setting1 }} {{ dns_setting2 }}"
              dns_search: "{{ dns_search }}"
              host_name: "{{ vm_name  }}"
              nic_on_boot: true
```
regards
rbertol
