### ISSUE TITLE
Add support for Ignition File using FedoraCoreOS (FCOS) or RHCOS 

### ISSUE THREAD

**Issue by anibal-aguila** [oVirt/ovirt-ansible-collection#157]
## It would be nice if the module allow passthrough Ignition file on the creation time, at the first boot.

> Fedora CoreOS (FCOS) Ignition files specify the configuration for provisioning FCOS instances. The process begins with a YAML configuration file. The FCOS Configuration Transpiler (FCCT) converts the human-friendly YAML file into machine-friendly JSON, which is the final configuration file for Ignition.

https://docs.fedoraproject.org/en-US/fedora-coreos/producing-ign/

## Some plan on the roadmap for this feature?

Thanks in advance,

**Comment by mnecas** [comment]
Hi @anibal-aguila,
thanks for the issue!
We already support the Ignition File but it is not documented.
You need to set the `operating_system` to `rhcos_x64` and then you can use `cloud_init` to pass data to the Ignition File.
Here is an example:
```yaml
    - name: ignition file example
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: test
        cluster: Default
        operating_system: rhcos_x64
        cloud_init_persist: True
        cloud_init:
          host_name: example.com
          custom_script: |
            write_files:
             - content: |
                 Hello, world!
               path: /tmp/greeting.txt
               permissions: '0644'
          user_name: root
          root_password: super_password
```
(`cloud_init_persist` if you want to check the values or have it permanent, or you can use state running and have the `cloud_init_persist` false)
