### ISSUE TITLE
ovirt_engine_setup_restore_engine_cleanup param hangs the role execution

### ISSUE THREAD

**Issue by jan-zmeskal** [oVirt/ovirt-ansible-collection#182]
I tried running following playbook against running engine:
```yaml
- hosts: jzmeskal_ansible_engine_1
  vars:
    ovirt_engine_setup_admin_password: <censored>
    ovirt_engine_setup_version: '4.4'
    ovirt_engine_setup_restore_engine_cleanup: true
    ovirt_engine_setup_restore_file: '/root/engine.backup'
    ovirt_engine_setup_restore_scopes:
      - 'all'
    ovirt_engine_setup_restore_options:
      log: '/root/ansible_restore.log'
      restore-permissions: ''
      provision-all-databases: ''

  roles:
    - ovirt.engine-setup
```

The result was that the role executing hung at task `TASK [ovirt.engine-setup : Run engine cleanup command]` for well over half an hour until I forcefully interrupted it with ^C. I suspect this is because `engine-cleanup` is an interactive command and expects some input from the user.
When I ran `engine-cleanup` manually and executed the above playbook again with `ovirt_engine_setup_restore_engine_cleanup` set to `false`, everything went fine.
