### ISSUE TITLE
ovirt_vm: host devices cannot be configured due to pinning requirement

### ISSUE THREAD

**Issue by snecklifter** [oVirt/ovirt-ansible-collection#186]
##### SUMMARY

When trying to set host devices, I received the following error:

`Cannot add Host devices. VM must be pinned to a host.`

This is despite setting host, placement policy as pinned and setting migrate to no.

##### COMPONENT NAME

ovirt_vm

##### STEPS TO REPRODUCE

Attempt to set host devices such as the documentation:

```
- name: Attach host devices to virtual machine
  ovirt_vm:
    name: myovirtvm
    host: myovirthost
    placement_policy: pinned
    host_devices:
      - name: pci_0000_00_07_0
        state: present
      - name: pci_0000_00_08_0
        state: present
```

##### EXPECTED RESULTS

Devices are passed through from host to VM.

##### ACTUAL RESULTS

Error above. I can configure manually in the RHV gui.

**Comment by snecklifter** [comment]
We have three VMs that need to use the same device IDs (FC cards) on each host.

**Comment by mnecas** [comment]
Hi @snecklifter,
I was not able to reproduce the issue I added the same host devices to multiple VMs and no issue.
Could you please show me the whole error?

**Comment by snecklifter** [comment]
@mnecas that is the whole error, which is produced from the following:

- name: Create Controller VMs
  ovirt_vm:
    timeout: 600
    auth:
      username: "{{ ovirt.username }}"
      password: "{{ ovirt.password }}"
      hostname: "{{ ovirt.hostname }}"
      insecure: "{{ ovirt.insecure }}"
    state: "{{ controller.state }}"
    template: "{{ controller.template }}"
    name: "{{ item.name }}"
    disk_format: "{{ ovirt.disk_format }}"
    clone: yes
    migrate: no
    placement_policy: pinned
    host_devices: "{{ controller.host_devices }}"
    cluster: "{{ ovirt.cluster }}"
    memory: "{{ controller.memory }}"
    cpu_cores: "{{ controller.cpu_cores }}"
    cpu_sockets: "{{ controller.cpu_sockets }}"
    type: server
    id: "{{ item.id }}"
    nics:
      - name: "{{ controller.nic_prov_name }}"
        profile_name: "{{ controller.nic_prov_profile_name }}"
        mac_address: "{{ item.mac }}"
      - name: "{{ controller.nic_mgmt_name }}"
        profile_name: "{{ controller.nic_mgmt_profile_name }}"
      - name: "{{ controller.nic_tenant_name }}"
        profile_name: "{{ controller.nic_tenant_profile_name }}"
      - name: "{{ controller.nic_api_name }}"
        profile_name: "{{ controller.nic_api_profile_name }}"
      - name: "{{ controller.nic_external_name }}"
        profile_name: "{{ controller.nic_external_profile_name }}"
      - name: "{{ controller.nic_stg_mgmt_name }}"
        profile_name: "{{ controller.nic_stg_mgmt_profile_name }}"
  with_items:
    - { host: "{{ controller.rhvhost_0 }}", name: "{{ controller.name_0}}", mac: "{{ controller.mac_0 }}", id: "{{ controller.id_0 }}" }
    - { host: "{{ controller.rhvhost_1 }}", name: "{{ controller.name_1}}", mac: "{{ controller.mac_1 }}", id: "{{ controller.id_1 }}" }
    - { host: "{{ controller.rhvhost_2 }}", name: "{{ controller.name_2}}", mac: "{{ controller.mac_2 }}", id: "{{ controller.id_2 }}" }

**Comment by snecklifter** [comment]
@mnecas I see that there is a note in:

https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.3/html-single/rest_api_guide/index#services-vm_host_device

``` A necessary precondition for a successful host device attachment is that the virtual machine must be pinned to exactly one host. The device ID is then taken relative to this host.```

Given that the pci device is identical for all three hosts, should we be using something unique to the host?

**Comment by mnecas** [comment]
Hi @snecklifter sorry for the late response.
I found out the issue please add the `host: YOUR_HOST` to the `ovirt_vm`
```yaml
    - name: Attach host devices to virtual machine
      ovirt.ovirt.ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: db-vm-3
        host: vhost2
        placement_policy: pinned
        host_devices:
          - name: pci_0000_00_07_0
            state: present
          - name: pci_0000_00_08_0
            state: present
```
