### ISSUE TITLE
Using kernel_path for unattended boot from ISO does nothing

### ISSUE THREAD

**Issue by bsolomon1124** [oVirt/ovirt-ansible-collection#189]
##### SUMMARY

Goal is to [automatically boot a VM from an ISO](https://simp.readthedocs.io/en/master/getting_started_guide/Installation_Options/ISO/Installing_SIMP_From_An_ISO.html#installing-the-os) similar to as is shown here:

https://github.com/lukepafford/ansible2/blob/1bddf7e1475cfe3c1c2c77bb947dfbf21a2105ef/playbooks/create_vm/create_vm.yml#L60

Using `ovirt_vm` with `kernel_path` in an effort to do an unattended boot from ISO does not seem to do anything. The VM is left in a running pre-boot state. All tasks are shown as OK or changed. 

The ISO is a customized derivative of the SIMP 6.4.0 ISO:

https://download.simp-project.com/simp/ISO/

/boot/grub2/grub.cfg shows the first menuentry as using `linux /vmlinuz-3.10.0-1160.2.1.el7.x86_64`.  The image exists at `/boot/vmlinuz-3.10.0-1160.2.1.el7.x86_64`.

##### COMPONENT NAME

ovirt_vm

##### STEPS TO REPRODUCE

```yaml
- name: test
  gather_facts: false
  hosts: localhost
  vars:
    ovirt_vm_name: ovirt_vm_test_01
    ovirt_disk_name: ovirt_disk_test_01
    memory: 128GiB
    disk_size: 250GiB
  tasks:
    - ovirt_auth:
        url: "https://{{ ovirt_engine_fqdn }}/ovirt-engine/api"
        username: redacted@redacted
        ca_file: "{{ ovirt_ca_bundle_file }}"
        password: "{{ ovirt_password }}"
        state: present
        timeout: 12
    - ovirt_disk:
        activate: true
        bootable: true
        ovirt_auth: "{{ ovirt_auth }}"
        name: "{{ ovirt_disk_name }}"
        size: "{{ disk_size }}"
        format: cow
        interface: virtio
        storage_domain: "{{ storage_domain }}"
        state: present
        wait: true
    - ovirt_vm:
        auth: "{{ ovirt_auth }}"
        state: present
        cluster: "{{ cluster }}"
        name: "{{ ovirt_vm_name }}"
        memory: "{{ memory }}"
        max_memory: "{{ memory }}"
        cd_iso: my-custom.iso
        boot_devices:
          - hd
          - cdrom
        disks:
          - name: "{{ ovirt_disk_name }}"
            bootable: true
        type: server
        usb_support: false
        operating_system: other_linux
        nics:
          - name: nic1
            profile_name: redacted
            interface: virtio
    - ovirt_vm:
        name: "{{ ovirt_vm_name }}"
        state: running
        auth: "{{ ovirt_auth }}"
        cluster: "{{ cluster }}"
        kernel_params: 'simp fips=0'
        kernel_path: 'iso://vmlinuz-3.10.0-1160.2.1.el7.x86_64'
        initrd_path: 'iso://initramfs-3.10.0-1160.2.1.el7.x86_64.img'
        kernel_params_persist: false
```

##### EXPECTED RESULTS

The VM should boot from the ISO automatically.

##### ACTUAL RESULTS

Instead I'm required to go into the Console from RVH-M UI and type `simp` to boot.
