### ISSUE TITLE
ovirt_host_network is not saving the network config.

### ISSUE THREAD

**Issue by kristvanbesien** [oVirt/ovirt-ansible-collection#216]
##### SUMMARY

After executing a ovirt_host_network task with save: yes set (wich should not even be needed) the host it has been executed for is flagged as "The Host network configuration is not saved."

##### COMPONENT NAME

ovirt_host_network
##### STEPS TO REPRODUCE
Applied the following task:

```yaml
- redhat.rhv.ovirt_host_network:
        auth: "{{ ovirt_auth }}"
        name: "{{ inventory_hostname }}"
        check: yes
        save: yes
        bond: 
          name: bond0
          mode: 4
          interfaces:
          - int0
          - int2
        networks:
        - name: ovirtmgmt
          boot_protocol: static
          address: "{{ private_ip }}"
          netmask: "{{ private_ip_cidr | ipaddr('netmask') }}"
          gateway: "{{ private_network_gateway }}"
        - name: Storage
          boot_protocol: static
          address: "{{ storage_ip }}"
          netmask: "{{ storage_ip_cidr | ipaddr('netmask') }}"
```

##### EXPECTED RESULTS

Network config is applied, and is saved.

##### ACTUAL RESULTS

Network config was applied. But host was flagged with "The Host network configuration is not saved."
