### ISSUE TITLE
Give an option to fetch all nested_attributes for modules with fetch_nested

### ISSUE THREAD

**Issue by WsevoL0D** [oVirt/ovirt-ansible-collection#246]
Currently, since ansible 2.9, I think, we need to explicitly specify a nested attributes in list for nested_attributes field, for corresponding module(usually ovirt*info) to load them. The problem is that occasionally the names of desired attributes are not obvious.
Currently the ways are: 
to guess attributes names (most of the times they are pretty obvious, but not always)
check in older ansible version, which fetches all attributes by default.

I suggest to add keyword "all" to the list, as the way to tell the module to load all nested attrs (default behaviour for older versions).

That won't affect modules speed (as default behavior left as is)
Gives users a way to quickly figure out attribute names (alternative way to modify docs for each module with nested_attributes)
Gives users an elegant way to load all attributes if needed (alternative to provide all names in a list)

```yaml
    - name: "Gather full storage vm info"
      ovirt_storage_domain_info:
        auth: "{{ ovirt_auth }}"
        fetch_nested: true
        nested_attributes:
        - all
```
