### ISSUE TITLE
ovirt_disk does not work correctly with Ansible-2.9.17 and RHV 4.4+

### ISSUE THREAD

**Issue by frangdlt** [oVirt/ovirt-ansible-collection#309]
##### SUMMARY

When uploading sparse (qcow) disks on ansible 2.9.x , the upload tasks fails and ansible ovirt_disk module is unable to successfully complete the upload. If using a raw disk, the same upload happens successfully. Both types of upload work successfully with ansible-2.10.x and 2.11.x in the same environment.

##### COMPONENT NAME

ovirt_disk

##### STEPS TO REPRODUCE

Reproducer:

```yaml
---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Grab Ovirt Token
      ovirt_auth:
        url: https://localhost/ovirt-engine/api
        username: admin@internal
        password: supersecret
        insecure: True

    - name: upload disk
      ovirt_disk:
        auth: "{{ ovirt_auth }}"
        name: "{{ item.name }}"
        state: present
        upload_image_path: "{{ item.path }}"
        format: "{{ item.format }}"
        storage_domain: "data4"
        timeout: 3600
      with_items:
        - name: "test_cow.qcow2"
          path: "/root/rhel-8.4-x86_64-kvm.qcow2"
          format: cow
        - name:  "test_raw.raw"
          path: "/root/rhel-8.4-x86_64-kvm.raw"
          format: raw

    - name: Revoke Ovirt Token
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
```

##### EXPECTED RESULTS

Disks are uploaded successfully using Ansible 2.9.x (which incidentally is shipped with ovirt manager).

##### ACTUAL RESULTS

```
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1624439905.1259193-249084-274646263692915/ > /dev/null 2>&1 && sleep 0'                                 
The full traceback is:                                                                                                                                                       
Traceback (most recent call last):                                                                                                                                           
  File "/tmp/ansible_ovirt_disk_payload_pg1az2i8/ansible_ovirt_disk_payload.zip/ansible/modules/cloud/ovirt/ovirt_disk.py", line 756, in main                                
  File "/tmp/ansible_ovirt_disk_payload_pg1az2i8/ansible_ovirt_disk_payload.zip/ansible/modules/cloud/ovirt/ovirt_disk.py", line 489, in upload_disk_image
  File "/tmp/ansible_ovirt_disk_payload_pg1az2i8/ansible_ovirt_disk_payload.zip/ansible/modules/cloud/ovirt/ovirt_disk.py", line 428, in transfer
Exception: Error occurred while uploading image. The transfer is in finalizing_failure 
failed: [localhost] (item={'name': 'test_cow.qcow2', 'path': '/root/rhel-8.4-x86_64-kvm.qcow2', 'format': 'cow'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "activate": null,
            "auth": {
                "ca_file": null,
                "compress": true,
                "headers": null,
                "insecure": true,
                "kerberos": false,
                "timeout": 0,
                "token": "redacted",
                "url": "https://localhost/ovirt-engine/api"
            },
            "bootable": null,
            "content_type": "data",
            "description": null,
            "download_image_path": null,
            "fetch_nested": false,
            "force": false,
            "format": "cow",
            "host": null,
            "id": "20c30610-32a2-4eec-b15f-8212c4999af8",
            "image_provider": null,
            "interface": null,
            "logical_unit": null,
            "name": "test_cow.qcow2",
            "nested_attributes": [],
            "openstack_volume_type": null,                                                                                                                          [100/321]
            "poll_interval": 3,
            "profile": null,
            "quota_id": null,
            "shareable": null,
            "size": null,
            "sparse": null,
            "sparsify": null,
            "state": "present",
            "storage_domain": "data4",
            "storage_domains": null,
            "timeout": 3600,
            "upload_image_path": "/root/rhel-8.4-x86_64-kvm.qcow2",
            "vm_id": null,
            "vm_name": null,
            "wait": true,
            "wipe_after_delete": null
        }
    },
    "item": {
        "format": "cow",
        "name": "test-cow.qcow2",
        "path": "/root/rhel-8.4-x86_64-kvm.qcow2"
    },
    "msg": "Error occurred while uploading image. The transfer is in finalizing_failure"
}
```

From the ovirt-imageio logs it seems the qcow2 upload fails almost immediately after starting. Maybe the module is not getting the right ovirt upload ticket, or extending the validity of it.
