### ISSUE TITLE
"follows" parameter not working

### ISSUE THREAD

**Issue by jgreifenhagen** [oVirt/ovirt-ansible-collection#354]
##### SUMMARY
While trying to migrate from using "fetch_nested" and "nested_attributes" to "follows" I am running into the issue, that none of the selected lists are filled in the gathered data.

##### COMPONENT NAME
(from ovirt.ovirt collection v 1.6.4 via ansible-galaxy)

ovirt_datacenter_info
ovirt_cluster_info
ovirt_host_info
ovirt_network_info
ovirt_storage_domain_info

It works on
ovirt_vm_info

##### STEPS TO REPRODUCE

```yaml
      - name: Obtain token from RHV
        ovirt_auth:
          url: "{{ ovirt_url }}"
          username: "{{ ovirt_username }}"
          password: "{{ ovirt_password }}"
          state: present
        tags: always

      # Fetch the data from the ovirt API
      - name: Fetch the datacenters
        ovirt.ovirt.ovirt_datacenter_info:
          auth: "{{ ovirt_auth }}"
          # fetch_nested: yes
          follows: ['networks','permissions','iscsibonds','clusters','storagedomains']
        register: datacenters
        tags: always

      - name: Fetch the clusters
        ovirt.ovirt.ovirt_cluster_info:
          auth: "{{ ovirt_auth }}"
          # fetch_nested: yes
          follows: ['cpuprofiles','networkfilters','networks','permissions','affinitygroups','enabledfeatures']
        register: clusters
        tags: always

      - name: Fetch the hosts
        ovirt.ovirt.ovirt_host_info:
          auth: "{{ ovirt_auth }}"
          # fetch_nested: yes
          follows: ['devices','hooks','networkattachments','nics','numanodes','permissions','katelloerrata','fenceagents','storage']
        register: hosts
        tags: always

      - name: Fetch the VM's
        ovirt.ovirt.ovirt_vm_info:
          auth: "{{ ovirt_auth }}"
          # fetch_nested: yes
          follows: ['diskattachments','nics','snapshots','katelloerrata']
        register: vms
        tags: always

      - name: Fetch the VM disk info
        ovirt.ovirt.ovirt_disk_info:
          auth: "{{ ovirt_auth }}"
          # fetch_nested: yes
        register: disks
        tags: always

      - name: Fetch the networks
        ovirt.ovirt.ovirt_network_info:
          auth: "{{ ovirt_auth }}"
          # fetch_nested: yes
          # follows: ['permissions', 'vnic_profiles']
          follows: ['vnic_profiles']
        register: networks
        tags: always

      - name: Fetch the storage domains
        ovirt.ovirt.ovirt_storage_domain_info:
          auth: "{{ ovirt_auth }}"
          # fetch_nested: yes
          follows: [ 'disk_profiles', 'disk_snapshots', 'disks', 'permissions', 'storage_connections', 'templates', 'vms' ]
        register: storage
        tags: always

```

##### EXPECTED RESULTS
```json
{
  "changed": false,
  "ovirt_datacenters": [
    {
      "href": "/ovirt-engine/api/datacenters/###",
      "id": "###",
      "name": "XXX",
      "clusters": [
        {
          "id": "###"
        }
      ],
      "iscsi_bonds": [],
      "local": false,
      "mac_pool": {
        "id": "###",
        "href": "/ovirt-engine/api/macpools/###"
      },
      "networks": [
        {
          "id": "###"
        },
        {
          "id": "###"
        },
        {
          "id": "###"
        }
      ],
      "permissions": [
        {
          "id": "###"
        },
        {
          "id": "###"
        }
      ],
      "qoss": [],
      "quota_mode": "disabled",
      "quotas": [
        {
          "id": "###"
        }
      ],
      "status": "up",
      "storage_domains": [
        {
          "id": "###"
        },
        {
          "id": "###"
        }
      ],
      "storage_format": "v5",
      "supported_versions": [
        {
          "major": 4,
          "minor": 5
        }
      ],
      "version": {
        "major": 4,
        "minor": 5
      }
    },
    {...}
  ]
}
```

##### ACTUAL RESULTS

```json
{
  "changed": false,
  "ovirt_datacenters": [
    {
      "href": "/ovirt-engine/api/datacenters/###",
      "id": "###",
      "name": "XXX",
      "clusters": [],
      "iscsi_bonds": [],
      "local": false,
      "mac_pool": {
        "href": "/ovirt-engine/api/macpools/###",
        "id": "###"
      },
      "networks": [],
      "permissions": [],
      "qoss": [],
      "quota_mode": "disabled",
      "quotas": [],
      "status": "up",
      "storage_domains": [],
      "storage_format": "v5",
      "supported_versions": [
        {
          "major": 4,
          "minor": 5
        }
      ],
      "version": {
        "major": 4,
        "minor": 5
      }
    },
    {...}
  ]
}
```
