### ISSUE TITLE
Upload local image to disk and attach it to a VM does not work.

### ISSUE THREAD

**Issue by mmartinv** [oVirt/ovirt-ansible-collection#360]
##### SUMMARY

Upload local image to disk and attach it to a VM does not work. 
This is reproducible by using ovirt-engine 4.4.9.1-1.el8 version

##### COMPONENT NAME

ovirt_disk

##### STEPS TO REPRODUCE

Create a VM, upload a local image to a disk and attach it to the VM as described at the official documentation: 

```yaml
# Upload local image to disk and attach it to vm:
# Since Ansible 2.3
- ovirt.ovirt.ovirt_disk:
    auth: "{{ ovirt_auth }}"
    name: mydisk
    vm_name: myvm
    interface: virtio
    bootable: true
    size: 10GiB
    format: cow
    image_path: /path/to/mydisk.qcow2
    storage_domain: data
```

##### EXPECTED RESULTS

The local image is correctly uploaded to the disk and attached to the VM

##### ACTUAL RESULTS

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ovirtsdk4.Error: Fault reason is "Operation Failed". Fault detail is "[Cannot attach Virtual Disk: Disk is locked. Please try again later.]". HTTP response code is 409.
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Fault reason is \"Operation Failed\". Fault detail is \"[Cannot attach Virtual Disk: Disk is locked. Please try again later.]\". HTTP response code is 409."}
```
