### ISSUE TITLE
Ovirt_disks : cannot rename disk

### ISSUE THREAD

**Issue by sflotron** [oVirt/ovirt-ansible-collection#362]
##### SUMMARY

Since upgrading to version >= 1.6.0, we cannot rename disk

##### COMPONENT NAME

ovirt.ovirt.ovirt_disk

##### STEPS TO REPRODUCE

Call this ansible block 
```yaml
  - name: Rename OS disk
    ovirt.ovirt.ovirt_disk:
      auth: "{{ ovirt_auth }}"
      id: "{{ result_vm_after.ovirt_vms[0]['disk_attachments'][0]['id'] }}"
      storage_domain: "{{ datastore_cluster }}"
      name: "{{ inventory_hostname }}_os"
      vm_name: "{{ inventory_hostname }}"
```

##### EXPECTED RESULTS
The OS disk is renamed

##### ACTUAL RESULTS

The ansible instruction throw the following error

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ovirtsdk4.Error: Fault reason is "Operation Failed". Fault detail is "Updating disk attributes other than QCOW version is permitted only for disk-attachments, which reside under VMs.". HTTP response code is 409
```
