### ISSUE TITLE
ovirt_template.py assumes base template is always version_number 1

### ISSUE THREAD

**Issue by sonneveld** [oVirt/ovirt-ansible-collection#369]
##### SUMMARY

If multiple template versions are added, and then the base template is removed via the webadmin screen, ovirt_template.py does not allow you to create a new version. This seems to be because the new base template has a version number higher than 1.

##### COMPONENT NAME

ovirt_template.py

Using python-ovirt-engine-sdk4-4.3.4-2.el7.x86_64 on centos7

##### STEPS TO REPRODUCE

Add a new template version. This is from a slightly modified version of the image_template role.

```yaml
   - name: Create template
      ovirt_template:
        auth: "{{ ovirt_auth }}"
        name: "{{ template_name }}"
        vm: "{{ vm_name }}"
        cluster: "{{ template_cluster }}"
        timeout: "{{ template_timeout }}"
        seal: "{{ template_seal }}"
        description: "{{ template_description }}"
        version:
          name: "{{ template_version }}"
      when: template_info.ovirt_templates | length > 0
      tags:
        - ovirt-template-image
```

Remove the base template,

rerun above task.

##### EXPECTED RESULTS

A new template is added.

##### ACTUAL RESULTS

```paste below
TASK [image_template : debug] *****************************************************************************************************************************************************************************************************************************
ok: [localhost] =>
  template_version: 20211022T134948

TASK [image_template : Create template] *******************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Error: Fault reason is "Incomplete parameters". Fault detail is "TemplateVersion [baseTemplate] required for addFromVm". HTTP response code is 400.
fatal: [localhost]: FAILED! => changed=false
  msg: Fault reason is "Incomplete parameters". Fault detail is "TemplateVersion [baseTemplate] required for addFromVm". HTTP response code is 400.


```
