### ISSUE TITLE
ovirt_auth garbles API URL if it contains password string

### ISSUE THREAD

**Issue by mz-pdm** [oVirt/ovirt-ansible-collection#379]
##### SUMMARY

When Engine password is a substring of the API URL, e.g. "ovirt", ovirt_auth replaces the given part of the URL with asterisks in provided facts. This means that although ovirt_auth successfully authenticates, it's impossible to use ``auth: "{{ ovirt_auth }}"`` in followup tasks, because the API URL is garbled with the asterisks.
 
##### COMPONENT NAME

ovirt.ovirt.ovirt_auth

##### STEPS TO REPRODUCE

Set Engine password to ``ovirt`` and run the following playbook:

```
  tasks:
    - block:
        - name: Obtain SSO token
          ovirt.ovirt.ovirt_auth:
            hostname: "{{ ansible_hostname }}"
            username: admin@internal
            password: ovirt

        - name: Add new data center
          ovirt.ovirt.ovirt_datacenter:
            name: mydatacenter
            local: False
            auth: "{{ ovirt_auth }}"

      always:
        - name: Revoke SSO token
          ovirt.ovirt.ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"
```

##### EXPECTED RESULTS

The playbook runs successfully.

##### ACTUAL RESULTS

The playbook fails with:

```An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ovirtsdk4.Error: The response content type 'text/html; charset=iso-8859-1' isn't the expected XML. Is the path '/********-engine/api' included in the 'url' parameter correct? The typical one is '/ovirt-engine/api'
fatal: [centos-engine]: FAILED! => {"changed": false, "msg": "The response content type 'text/html; charset=iso-8859-1' isn't the expected XML. Is the path '/********-engine/api' included in the 'url' parameter correct? The typical one is '/ovirt-engine/api'"}
```

ovirt_auth facts are:

```
    "ansible_facts": {
        "ovirt_auth": {
            "ca_file": null,
            "compress": true,
            "headers": null,
            "insecure": true,
            "kerberos": false,
            "timeout": 0,
            "token": "...",
            "url": "https://centos-engine/********-engine/api"
        }
```
