### ISSUE TITLE
ovirt_vm_info fails with "The response content type 'text/html;charset=UTF-8' isn't the expected XML"

### ISSUE THREAD

**Issue by jangel97** [oVirt/ovirt-ansible-collection#407]
# SUMMARY
Hi, module _ovirt_vm_info_ is failing with error: `The response content type 'text/html;charset=UTF-8' isn't the expected XML`.

Environment:
```
Python version: 3.6.8
Ansible version: 2.9.11
ovirt-engine-sdk-python version: 4.4.14 
```

My RHV instance **has digital certificate expired**. Even though,`ovirt_auth` has entry `insecure` set to `true`  the error is still happening. Is this a bug? Or is it something I am missing?

# STEPS TO REPRODUCE

```yaml
   - name: Authenticating to RHV at {{ rhv_host }}
     ovirt_auth:
       url: "https://{{ rhv_host }}/ovirt-engine/api"
       insecure: true
       kerberos: true
    - name: Get all rhv vms
      ovirt_vm_info:
        auth: "{{ ovirt_auth }}"
      register: all_rhv_vms
```

##### EXPECTED RESULTS

I would expect the previous code to run successfully (even with the RHV instance with cert epired), but I am finding the following error:
```
The response content type 'text/html;charset=UTF-8' isn't the expected XML
``` 

Is this a bug, could it be that I am missing something? If this is a bug, is there something I can do to bypass it temporarily?

Thanks in advance,
