### ISSUE TITLE
Stuck at Wait for the local VM when using password based login

### ISSUE THREAD

**Issue by xrow** [oVirt/ovirt-ansible-collection#408]
##### SUMMARY

This command works and doesn`t get stuck.
/usr/bin/ansible-playbook ovirt-hosted-engine.yml -i hosts --key-file "~/.ssh/id_ed25519"

If I use this command /usr/bin/ansible-playbook ovirt-hosted-engine.yml -i hosts the installer gets stuck at:

TASK [ovirt.ovirt.hosted_engine_setup : Wait for the local VM] *****************************

##### STEPS TO REPRODUCE

```yaml
- name: Deploy oVirt hosted engine
  hosts: server005.dc02.xxx.net
  vars:
    he_appliance_password: centos
    he_admin_password: centos
    he_fqdn: "ovirt-engine-01.xxx.net"
    he_ansible_host_name: "server005.dc02.xxx.net"
    he_domain_type: "nfs"
    he_storage_domain_addr: "192.168.0.251"
    he_storage_domain_path: "/volume5/Data/vms"
    he_vcpus: 2

    # Static IP configuration Variables
    he_bridge_if: "enp4s0f0"
    he_vm_ip_addr: "192.168.222.176"
    he_ipv4_subnet_prefix: "192.168.222"
    he_vm_mac_addr: "00:16:3e:76:ee:d6"
    he_vm_ip_prefix: "24"
    he_dns_addr: "192.168.0.220"
    he_default_gateway: "10.11.0.1"
    he_vm_etc_hosts: true
  roles:
    - role: hosted_engine_setup
  collections:
    - ovirt.ovirt
```

##### EXPECTED RESULTS

Not get stuck

##### ACTUAL RESULTS

```paste below
Timeout password login error
```

Cna you reproduce it?
