### ISSUE TITLE
Unable to create a shared virtual disk

### ISSUE THREAD

**Issue by cmcwales2k** [oVirt/ovirt-ansible-collection#416]
##### SUMMARY
I have a storage domain on which I need to create a shared disk which will be utilised by 2 or more servers. Via the web UI this works fine, however via ansible I can only create none sharable disks.

In ansible when I use "shareable: yes" it fails, when I use "shareable: no" works.

version: ovirt-engine-sdk-python 4.5.0

##### COMPONENT NAME
ovirt.ovirt.ovirt_disk

##### STEPS TO REPRODUCE

```yaml


Minimal extract from playbooks
vars:
  vdisks:
    - name: 'shareddisk1'
      state: 'present'
      storage_domain: data
      size: '50GiB'
      interface: virtio
      format: cow
      shareable: yes
      activate: no
      sparse: no  
tasks:
    - ovirt.ovirt.ovirt_disk:
        auth: "{{ ovirt_auth }}"
        name: "{{ item.name }}"
        vm_name: "{{ item.vm_name | default(omit)}}"
        size: "{{ item.size }}"
        interface: "{{ item.interface }}"
        storage_domain: "{{ item.storage_domain }}"
        format: "{{ item.format| default(omit) }}"
        state: "{{ item.state }}"
        shareable: "{{ item.shareable }}"
        activate: "{{ item.activate }}"
      loop: "{{ vdisks }}"

collections:
    - ovirt.ovirt

```

##### EXPECTED RESULTS
A shareable virtual disk to be created on a storage domain

##### ACTUAL RESULTS

```paste below
TASK [ovirt.ovirt.ovirt_disk] ***************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ovirtsdk4.Error: Fault reason is "Operation Failed". Fault detail is "[Cannot add Virtual Disk. Disk's volume format is not supported for shareable disk.]". HTTP response code is 409.
[WARNING]: Module did not set no_log for pass_discard
failed: [localhost] (item={'name': 'shareddisk1', 'state': 'present', 'storage_domain': 'data', 'size': '50GiB', 'interface': 'virtio', 'format': 'cow', 'shareable': True, 'activate': False, 'sparse': False}) => changed=false
  ansible_loop_var: item
  item:
    activate: false
    format: cow
    interface: virtio
    name: shareddisk1
    shareable: true
    size: 50GiB
    sparse: false
    state: present
    storage_domain: data
  msg: Fault reason is "Operation Failed". Fault detail is "[Cannot add Virtual Disk. Disk's volume format is not supported for shareable disk.]". HTTP response code is 409.

```
