### ISSUE TITLE
cluster upgrade fails

### ISSUE THREAD

**Issue by sjd78** [oVirt/ovirt-ansible-collection#476]
##### SUMMARY

Cluster upgrade role starts to run but fails on the first "Update the upgrade progress on the cluster" task.

##### COMPONENT NAME

cluster_upgrade

##### STEPS TO REPRODUCE

```yaml
---
- name: oVirt cluster upgrade wizard target
  hosts: localhost
  remote_user: root
  gather_facts: false

  vars:
    cluster_name: Cluster_DC-2_A
    host_names:
      - host3

    stop_non_migratable_vms: true
    upgrade_timeout: 3600
    check_upgrade: true
    reboot_after_upgrade: true
    use_maintenance_policy: true

    engine_url: https://ENGINE.FQDN/ovirt-engine/api
    engine_insecure: true
    engine_user: admin@internal
    engine_password: THEPASSWORD

  roles:
    - cluster_upgrade

  collections:
    - ovirt.ovirt
```

##### EXPECTED RESULTS

Upgrade runs to completion and the progress is logged via events and via the new 4.5 rest endpoint.

##### ACTUAL RESULTS

```
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [oVirt cluster upgrade wizard target] *****************************************************************************************************************************************************

TASK [ovirt.ovirt.cluster_upgrade : Initialize variables] **************************************************************************************************************************************
ok: [localhost]

TASK [ovirt.ovirt.cluster_upgrade : Login to oVirt] ********************************************************************************************************************************************
ok: [localhost]

TASK [ovirt.ovirt.cluster_upgrade : progress 0% - need to do info lookups] *********************************************************************************************************************
included: /usr/share/ansible/collections/ansible_collections/ovirt/ovirt/roles/cluster_upgrade/tasks/log_progress.yml for localhost

TASK [ovirt.ovirt.cluster_upgrade : Log progress as an event] **********************************************************************************************************************************
changed: [localhost]

TASK [ovirt.ovirt.cluster_upgrade : Update the upgrade progress on the cluster] ****************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'api_gt45' failed. The error was: error while evaluating conditional (api_gt45): 'api_gt45' is undefined\n\nThe error appears to be in '/usr/share/ansible/collections/ansible_collections/ovirt/ovirt/roles/cluster_upgrade/tasks/log_progress.yml': line 25, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Update the upgrade progress on the cluster\n    ^ here\n"}

TASK [ovirt.ovirt.cluster_upgrade : Set cluster upgrade status to finished] ********************************************************************************************************************
skipping: [localhost]

TASK [ovirt.ovirt.cluster_upgrade : Logout from oVirt] *****************************************************************************************************************************************
ok: [localhost]

PLAY RECAP *************************************************************************************************************************************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
```
