### ISSUE TITLE
SSL Error - CA Not Validated - Engine Setup:

### ISSUE THREAD

**Issue by SnappsProject** [oVirt/ovirt-ansible-collection#494]
##### SUMMARY
i am trying to deploy olvm-self-hosted.
During the installation of the engine it is not possible to verify the correct functioning of the console because the certificate (self-signed) is not valid.

##### COMPONENT NAME

https://github.com/oVirt/ovirt-ansible-collection/blob/ed5531f6c13e9ca8e6c661066ee845da01d2f218/roles/engine_setup/tasks/engine_setup.yml#L106
##### STEPS TO REPRODUCE
```
hosted-engine --deploy
```
hosted-engine deploy fails because the http endpoint returns an SSL certificate verification error

Hosted Engine deploy - BUG
```yaml
  - name: Check if Engine health page is up
    uri:
      url: "http://localhost/ovirt-engine/services/health"
      status_code: 200
    register: health_page
    retries: 30
    delay: 10
    until: health_page is success
```
I solved it by adding the parameter validate_certs: false before the url declaration in this line:

Fix:

```yaml
  - name: Check if Engine health page is up
    uri:
      validate_certs: false
      url: "http://localhost/ovirt-engine/services/health"
      status_code: 200
    register: health_page
    retries: 30
    delay: 10
    until: health_page is success
```

##### EXPECTED RESULTS
OK

##### ACTUAL RESULTS
Currently with this change I have solved the problem.
