### ISSUE TITLE
ovirtvmipsv4 bug when using attr

### ISSUE THREAD

**Issue by piramix** [oVirt/ovirt-ansible-collection#593]
##### SUMMARY
When I use filter ovirtvmipsv4 with attr then I'm getting wrong results (ips are missing)

##### COMPONENT NAME
ovirtmipsv4 filter

##### STEPS TO REPRODUCE

```yaml
  tasks:
    - ovirt.ovirt.ovirt_vm_info:
        pattern: name=nl*
        auth: "{{ ovirt_auth }}"
        follow: ['reported_devices']
      register: vms
    - name: Print VM IP
      debug:
        msg: "{{ vms.ovirt_vms | ovirt.ovirt.ovirtvmipsv4(attr='name') }}"
```

##### EXPECTED RESULTS
TASK [Print VM IP] **********************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "nlx1": [
            "10.46.15.47"
        ],
        "nlx2": [
            "10.46.15.48"
        ],

##### ACTUAL RESULTS

```paste below
TASK [Print VM IP] **********************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "nlx1",
        "nlx2",
        "nlx3",
        "nlx4",
```

Code:

```
    def ovirtvmipsv4(self, ovirt_vms, attr=None, network_ip=None):
        'Return list of IPv4 IPs'
        ips = self._parse_ips(ovirt_vms, lambda version: version == 'v4', attr)
        resp = [ip for ip in ips if self.__address_in_network(ip, network_ip)]
        return resp
```

This code is returning resp instead of ips and if you will use any attr you'll get wrong results
Proper behavior is when I modified the code and removed resp line and use return ips.

```
    def ovirtvmipsv4(self, ovirt_vms, attr=None, network_ip=None):
        'Return list of IPv4 IPs'
        ips = self._parse_ips(ovirt_vms, lambda version: version == 'v4', attr)
        return ips
```
