### ISSUE TITLE
ovirt_disk module: Failed to upload local QCOW/ISO to oVirt engine  [Errno 36] File name too long

### ISSUE THREAD

**Issue by Gounick** [oVirt/ovirt-ansible-collection#616]
##### SUMMARY

Hello, I want to load a QCOW2 or ISO disk image from the Ansible controller to oVirt engine.

Only ovirt.ovirt v1.6.6 collection works. Others from 2.0.0 to latest 2.3.1 fail with "The file is too long" message.

##### COMPONENT NAME

* oVirt Open Virtualization Manager
```
v4.3.9.4-1.el7
```

* requirements.yml :

```yaml
---
collections:
  - name: ovirt.ovirt
    version: 2.3.1
    #KO# version: 2.2.3
    #KO# version: 2.2.2
    #KO# version: 2.2.1
    #KO# version: 2.1.0
    #KO# version: 2.0.4
    #KO# version: 2.0.3
    #KO# version: 2.0.2
    #KO# version: 2.0.1
    #KO# version: 2.0.0
    #OK# version: 1.6.6
  - name: ansible.utils
  - name: community.general

```

* Pipfile:

```ini
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
ansible-core = "==2.12.*"
jmespath = "*"
netaddr = "*"
ovirt_imageio = ">=2.4.6"
ovirt-engine-sdk-python = "==4.5.*"

[dev-packages]

[requires]
python_version = "3.8"
```

* `$ pipenv run pip freeze` :
```
ansible-core==2.12.10
cffi==1.15.1
cryptography==38.0.3
Jinja2==3.1.2
jmespath==1.0.1
MarkupSafe==2.1.1
netaddr==0.8.0
ovirt-engine-sdk-python==4.5.2
ovirt-imageio==2.4.6
packaging==21.3
pycparser==2.21
pycurl==7.45.1
pyparsing==3.0.9
PyYAML==6.0
resolvelib==0.5.4
six==1.16.0
```

* `$ pipenv run ansible-galaxy collection list`:
```
# /home/me/.ansible/collections/ansible_collections
Collection             Version
---------------------- -------
ansible.netcommon      3.1.3  
ansible.posix          1.3.0  
ansible.utils          2.7.0  
community.crypto       2.0.1  
community.general      6.0.0  
ovirt.ovirt            2.3.1
```

##### STEPS TO REPRODUCE

```yaml
- name: Dowload debian-11-genericcloud-amd64.qcow2 image
  ansible.builtin.get_url:
    url: https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-amd64.qcow2
    dest: /tmp/debian-11-genericcloud-amd64.qcow2
    mode: 0644
 
- name: Login to oVirt
  ovirt.ovirt.ovirt_auth:
    hostname: "{{ engine_fqdn }}"
    username: "{{ engine_user }}"
    password: "{{ engine_password }}"
    ca_file: "{{ engine_cafile | default(omit) }}"
    insecure: "{{ engine_insecure | default(true) }}"
  vars:
    engine_cafile: "{{ lookup('url', 'https://{{ engine_fqdn }}/ovirt-engine/services/pki-resource?resource=ca-certificate&format=X509-PEM-CA', validate_certs=false) }}"
    engine_insecure: true
    engine_port: 443
 
- name: "Deploy the disk image to oVirt engine on storage16 storage domain"
  ovirt.ovirt.ovirt_disk:
    auth: "{{ ovirt_auth }}"
    content_type: data
    force: false
    name: debian-11-genericcloud-amd64
    size: 2GiB
    max_workers: 10
    upload_image_path: /tmp/debian-11-genericcloud-amd64.qcow2
    storage_domain: storage16
  register: result_ovirt_disk_disk
```

##### EXPECTED RESULTS
Image uploaded.

##### ACTUAL RESULTS

```
TASK [ovirt_upload_image : Deploy the disk image to oVirt engine on storage16 storage domain] ************************************************
task path: /home/me/ansible-ovirt/roles/ovirt_upload_image/tasks/disk.yml:8
The full traceback is:
Traceback (most recent call last):
  File "/home/me/.virtualenvs/ansible-ovirt-NUnXWz5g/lib/python3.8/site-packages/ovirt_imageio/client/_api.py", line 523, in _open_http
    return http.open(url, mode, cafile=cafile, secure=secure)
  File "/home/me/.virtualenvs/ansible-ovirt-NUnXWz5g/lib/python3.8/site-packages/ovirt_imageio/_internal/backends/http.py", line 51, in open
    return Backend(url, **options)
  File "/home/me/.virtualenvs/ansible-ovirt-NUnXWz5g/lib/python3.8/site-packages/ovirt_imageio/_internal/backends/http.py", line 79, in __init__
    self._connect()
  File "/home/me/.virtualenvs/ansible-ovirt-NUnXWz5g/lib/python3.8/site-packages/ovirt_imageio/_internal/backends/http.py", line 119, in _connect
    self._context = self._create_ssl_context()
  File "/home/me/.virtualenvs/ansible-ovirt-NUnXWz5g/lib/python3.8/site-packages/ovirt_imageio/_internal/backends/http.py", line 369, in _create_ssl_context
    context = ssl.create_default_context(
  File "/home/me/.pyenv/versions/3.8.12/lib/python3.8/ssl.py", line 745, in create_default_context
    context.load_verify_locations(cafile, capath, cadata)
OSError: [Errno 36] File name too long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ansible_ovirt.ovirt.ovirt_disk_payload_ko9v7swq/ansible_ovirt.ovirt.ovirt_disk_payload.zip/ansible_collections/ovirt/ovirt/plugins/modules/ovirt_disk.py", line 906, in main
  File "/tmp/ansible_ovirt.ovirt.ovirt_disk_payload_ko9v7swq/ansible_ovirt.ovirt.ovirt_disk_payload.zip/ansible_collections/ovirt/ovirt/plugins/modules/ovirt_disk.py", line 602, in upload_disk_image
  File "/tmp/ansible_ovirt.ovirt.ovirt_disk_payload_ko9v7swq/ansible_ovirt.ovirt.ovirt_disk_payload.zip/ansible_collections/ovirt/ovirt/plugins/modules/ovirt_disk.py", line 592, in upload_disk_image
  File "/home/me/.virtualenvs/ansible-ovirt-NUnXWz5g/lib/python3.8/site-packages/ovirt_imageio/client/_api.py", line 81, in upload
    with _open_http(
  File "/home/me/.virtualenvs/ansible-ovirt-NUnXWz5g/lib/python3.8/site-packages/ovirt_imageio/client/_api.py", line 531, in _open_http
    return http.open(url, mode, cafile=cafile, secure=secure)
  File "/home/me/.virtualenvs/ansible-ovirt-NUnXWz5g/lib/python3.8/site-packages/ovirt_imageio/_internal/backends/http.py", line 51, in open
    return Backend(url, **options)
  File "/home/me/.virtualenvs/ansible-ovirt-NUnXWz5g/lib/python3.8/site-packages/ovirt_imageio/_internal/backends/http.py", line 79, in __init__
    self._connect()
  File "/home/me/.virtualenvs/ansible-ovirt-NUnXWz5g/lib/python3.8/site-packages/ovirt_imageio/_internal/backends/http.py", line 119, in _connect
    self._context = self._create_ssl_context()
  File "/home/me/.virtualenvs/ansible-ovirt-NUnXWz5g/lib/python3.8/site-packages/ovirt_imageio/_internal/backends/http.py", line 369, in _create_ssl_context
    context = ssl.create_default_context(
  File "/home/me/.pyenv/versions/3.8.12/lib/python3.8/ssl.py", line 745, in create_default_context
    context.load_verify_locations(cafile, capath, cadata)
OSError: [Errno 36] File name too long
[WARNING]: Module did not set no_log for pass_discard
fatal: [ovirt3]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "activate": null,
            "auth": {
                "ca_file": "-----BEGIN CERTIFICATE-----,**************************,-----END CERTIFICATE-----",
                "compress": true,
                "headers": null,
                "hostname": null,
                "insecure": true,
                "kerberos": false,
                "password": null,
                "timeout": 0,
                "token": "**************************",
                "url": "https://**************************/ovirt-engine/api",
                "username": null
            },
            "backup": null,
            "bootable": null,
            "content_type": "data",
            "description": null,
            "download_image_path": null,
            "fetch_nested": false,
            "force": false,
            "format": "cow",
            "host": null,
            "id": "716e2aa9-4b84-41e8-91c7-b707be56ea9d",
            "image_provider": null,
            "interface": null,
            "logical_unit": null,
            "max_workers": 10,
            "name": "debian-11-genericcloud-amd64",
            "nested_attributes": [],
            "openstack_volume_type": null,
            "pass_discard": null,
            "poll_interval": 3,
            "profile": null,
            "propagate_errors": null,
            "quota_id": null,
            "read_only": null,
            "scsi_passthrough": null,
            "shareable": null,
            "size": "2GiB",
            "sparse": null,
            "sparsify": null,
            "state": "present",
            "storage_domain": "storage16",
            "storage_domains": null,
            "timeout": 180,
            "upload_image_path": "/tmp/debian-11-genericcloud-amd64.qcow2",
            "uses_scsi_reservation": null,
            "vm_id": null,
            "vm_name": null,
            "wait": true,
            "wipe_after_delete": null
        }
    },
    "msg": "[Errno 36] File name too long"
}

```
Best regard
