### ISSUE TITLE
Add bios_type parameter to role image_template

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-ansible-collection#619]
##### SUMMARY
Add bios_type parameter to role image_template

##### COMPONENT NAME
role image_template

##### ADDITIONAL INFORMATION
RHEL 7.9 can't run with UEFI bios type, so we need to set the template to Legacy
https://docs.ansible.com/ansible/latest/collections/ovirt/ovirt/ovirt_template_module.html#parameter-bios_type

```yaml
    - name: ovirt image template role
      include_role:
        name: ovirt.ovirt.image_template
      vars:
        engine_url: "{{ api_url }}"
        engine_user: "{{ username }}"
        engine_password: "{{ password }}"
        template_name: "{{ item.name }}"
        template_disk_name: "{{ item.name }}"
        glance_image_provider: "{{ item.image_provider }}"
        glance_image: "{{ item.image_disk }}"
        template_disk_storage: "{{ item.storage_domain }}"
        template_cluster: "{{ item.cluster }}"
        template_operating_system: "{{ item.operating_system | default(omit) }}"
        template_memory: "{{ item.memory | default(omit) }}"
        template_memory_max: "{{ item.memory_max | default(omit) }}"
        template_memory_guaranteed: "{{ item.memory_guaranteed | default(omit) }}"
        template_io_threads: "{{ item.template_io_threads | default(omit) }}"
        template_timeout: 3600
        template_bios_type: q35_sea_bios
      with_items: "{{ ext }}"

```
