### ISSUE TITLE
Add support for disk_format and extend support for storage_domain to ovirt_template module

### ISSUE THREAD

**Issue by Gounick** [oVirt/ovirt-ansible-collection#631]
##### SUMMARY

The module `ovirt_template` should be extended to support :
* [disk_format](https://docs.ansible.com/ansible/latest/collections/ovirt/ovirt/ovirt_vm_module.html#parameter-disk_format) parameter like the [ovirt_vm](https://docs.ansible.com/ansible/latest/collections/ovirt/ovirt/ovirt_vm_module.html) module
* [storage_domain](https://docs.ansible.com/ansible/latest/collections/ovirt/ovirt/ovirt_template_module.html#parameter-storage_domain) parameter when:
  * state=present
  * template do not exist
  * vm is defined (=template created from VM)

##### COMPONENT NAME
[ovirt_template](https://docs.ansible.com/ansible/latest/collections/ovirt/ovirt/ovirt_template_module.html)

##### ADDITIONAL INFORMATION
Currently [storage_domain](https://docs.ansible.com/ansible/latest/collections/ovirt/ovirt/ovirt_template_module.html#parameter-storage_domain) parameter only works when `state=registered`, which implies that the model already exists..

The objective is to be able to define the `storage_domain` destination and the format (cow or raw) of the disks when the template is created from a VM. Currently, the `storage_domain` destination is the same as the source VM..

This is possible from the 4.3 to latest oVirt version according to the [API doc](https://ovirt.github.io/ovirt-engine-api-model/4.3/#services/templates/methods/add).

```yaml
- name: Create a template from a VM on a different storage_domain than the source VM
  ovirt.ovirt.ovirt_template:
    cluster: mycluster
    name: mytemplate
    vm: myvm
    storage_domain: mystorage
    disk_format: raw  # cow or raw
```
