### ISSUE TITLE
Allow default_route usage to be configurable via the ovirt_network module

### ISSUE THREAD

**Issue by ilush** [oVirt/ovirt-ansible-collection#648]
##### SUMMARY
Allow default_route usage to be configurable via the ovirt_network module

It is already present in API[1] and SDK[2], but not in ansible yet.
[1] <http://ovirt.github.io/ovirt-engine-api-model/master/#types/network_usage>
[2] <https://github.com/oVirt/python-ovirt-engine-sdk4/blob/main/lib/ovirtsdk4/types.py#L26156>

##### COMPONENT NAME
ovirt_network module

##### ADDITIONAL INFORMATION
This would allow changing the default route for the hosts

```yaml
- ovirt.ovirt.ovirt_network:
    data_center: mydatacenter
    name: mynetwork
    vlan_tag: 10
    vm_network: true
    clusters:
      - name: myshinycluster
        default_route: true
```
