### ISSUE TITLE
ovirt_storage_domain_info: Retrieve status attribute

### ISSUE THREAD

**Issue by Gounick** [oVirt/ovirt-ansible-collection#658]
##### SUMMARY

Retrieve `status` attribute of Storage Domain.

I need to know if a storage domain is under maintenance or not: `status` attribute contains the information sought.

##### COMPONENT NAME

[ovirt.ovirt.ovirt_storage_domain_info](https://docs.ansible.com/ansible/latest/collections/ovirt/ovirt/ovirt_storage_domain_info_module.html) module

##### ADDITIONAL INFORMATION

The API document describes an endpoint to retrieve this information:

- https://ovirt.github.io/ovirt-engine-api-model/4.3/#types/storage_domain_status
- https://ovirt.github.io/ovirt-engine-api-model/4.4/#types/storage_domain_status
- https://ovirt.github.io/ovirt-engine-api-model/4.5/#types/storage_domain_status

but this `/ovirt-engine/api/storagedomains/<id>` endpoint does not show it.

We have to go through another endpoint to retrieve it : `/ovirt-engine/api/datacenters/<id>/storagedomains`

##### VERSION

* oVirt engine 4.3 and 4.4
* Latest SDK Python (pip package)
* Latest ovirt.ovirt collection
* Ansible 2.12 (pip package)
* Python 3.10

###### `status` attribute does not exist:

```yaml
- name: "Fetch the datacenter name associated with {{ cluster }} cluster."
  ovirt.ovirt.ovirt_datacenter_info:
    auth: "{{ ovirt_auth }}"
    pattern: "Clusters.name = {{ cluster }}"
  register: result_ovirt_datacenter_info

- name: Retrieve information about storage domains
  ovirt.ovirt.ovirt_storage_domain_info:
    auth: "{{ ovirt_auth }}"
    pattern: "datacenter={{ result_ovirt_datacenter_info.ovirt_datacenters[0].name }}"
    fetch_nested: true
  register: result_ovirt_storage_domain_info

- ansible.builtin.debug:
    var: result_ovirt_storage_domain_info.ovirt_storage_domains
          | selectattr('status', 'defined')
          | selectattr('status', 'equalto', 'active')
```

###### `status` attribute is present:

```yaml
- name: "Fetch the datacenter name associated with {{ cluster }} cluster."
  ovirt.ovirt.ovirt_datacenter_info:
    auth: "{{ ovirt_auth }}"
    pattern: "Clusters.name = {{ cluster }}"
  register: result_ovirt_datacenter_info

- name: Retrieve information about storage domains
  ansible.builtin.uri:
    url: "https://{{ engine_fqdn + result_ovirt_datacenter_info.ovirt_datacenters[0].href }}/storagedomains"
    method: GET
    validate_certs: false
    body_format: json
    headers:
      Accept: application/json
      Authorization: "Bearer {{ ovirt_auth.token }}"
  register: result_ovirt_storage_domain_info

- ansible.builtin.debug:
    var: result_ovirt_storage_domain_info.json.storage_domain
          | selectattr('status', 'defined')
          | selectattr('status', 'equalto', 'active')
```

##### EXPECTED RESULTS

Retrieve the `status` attribute of a Storage Domain as described in the API documentation.
