### ISSUE TITLE
cluster_info module returns nothing

### ISSUE THREAD

**Issue by ingvarrwvw** [oVirt/ovirt-ansible-collection#683]
##### SUMMARY
Using module version 3.1.0
Need to get information about clusters
##### COMPONENT NAME
ovirt.ovirt.ovirt_cluster_info
##### STEPS TO REPRODUCE
Taking an example from the documentation :
```
- ovirt.ovirt.ovirt_cluster_info:
    pattern:
      name: 'production*'
  register: result
- ansible.builtin.debug:
    msg: "{{ result.ovirt_clusters }}"
```

##### EXPECTED RESULTS
info about clusters with name 'production-1*'

##### ACTUAL RESULTS
"msg": []
```paste below

```

**Comment by mnecas** [comment]
The pattern should be string, not dict.
```
    - ovirt.ovirt.ovirt_cluster_info:
        auth: "{{ ovirt_auth }}"
        pattern: "name=production*"
      register: result
    - ansible.builtin.debug:
        msg: "{{ result.ovirt_clusters }}"
```
sorry about the example will fix it
