### ISSUE TITLE
The snapshot is not deleted by the ovirt.ovirt.ovirt_snapshot module

### ISSUE THREAD

**Issue by zzayale** [oVirt/ovirt-ansible-collection#744]
##### SUMMARY
The snapshot is not deleted by the ```ovirt.ovirt.ovirt_snapshot``` module

##### COMPONENT NAME
```ovirt.ovirt.ovirt_snapshot```
##### STEPS TO REPRODUCE
Snapshot on this test machine was created Mar 19, 2020, 3:05:56 PM
```yaml
    ovirt_snapshot_vms:
      - name: test-vm
        snapshots_old: 3
```
```yaml
    - name: Remove snapshots
      ovirt.ovirt.ovirt_snapshot:
        vm_name: "{{ item.name }}"
        keep_days_old: "{{ item.snapshots_old }}"
        auth: "{{ ovirt_auth }}"
      with_items: "{{ ovirt_snapshot_vms }}"
      delegate_to: localhost
```

##### ACTUAL RESULTS

```paste below

```
