### ISSUE TITLE
template support for ovirt_tag

### ISSUE THREAD

**Issue by gstorme** [oVirt/ovirt-ansible-collection#765]
##### SUMMARY
The ovirt_tag module currently only supports virtual machines, not templates.
Can the module be extended to support assigning tags to templates as well?

##### COMPONENT NAME
ovirt_tag

##### ADDITIONAL INFORMATION

Example 1

```yaml
  - ovirt.ovirt.ovirt_tag:
      auth: "{{ ovirt_auth }}"
      name: myTag
      template: true
      vms:
        - windows2025_template
```

Example 2
```yaml
  - ovirt.ovirt.ovirt_tag:
      auth: "{{ ovirt_auth }}"
      name: myTag
      templates:
        - windows2025_template
```
