### ISSUE TITLE
ovirt_disk: Provide option to configure direct LUN with SCSI Pass-Through

### ISSUE THREAD

**Issue by mattpoel** [oVirt/ovirt-ansible-collection#89]
##### SUMMARY
When creating a direct LUN for a virtual machine, ovirt web interface provides the option to enable SCSI Pass-Through (enabled by default in this dialog):

<img width="929" alt="ovirt_new_direct_LUN" src="https://user-images.githubusercontent.com/15014728/90552916-db112f00-e193-11ea-9d2f-eac865abff6c.png">

ovirt_disk currently has no option to configure SCSI Pass-Through for a direct LUN. Can this option be added like with shareable?

##### COMPONENT NAME
ovirt_disk

##### ADDITIONAL INFORMATION
A "SCSI Pass-Through" option will be used to configure a direct LUN for SCSI Pass-Through.

```yaml
  - name: VM -> Add SCSI Pass-Through Direct LUN
    ovirt_disk:
      auth:
        username: "admin@internal"
        password: "password"
        insecure: yes
        url: "https://ovirt.domain/ovirt-engine/api"

      name: "testvm_TEST01"
      host: "testhost"
      interface: virtio_scsi
      shareable: yes
      scsi_passthrough: yes
      vm_name: "testvm"
      format: raw
      logical_unit:
        id: "36000xxxxd38"
        storage_type: fcp
```
